### ISSUE TITLE
Misleading usage in README.md

### ISSUE THREAD

**Issue by omrisarig13** [pimoroni/apa102-python#6]
Hello,

First of all, thank you very much for this library, it works great.

Unfortunately, I found the example provided in the README.md file very misleading.
According to what I understood from this example, calling the function `lights.set_pixel(...)` should change the light of the LED in the given position.
However, this function only sets the internal buffer, and to actually change the values of the LEDs a call to `lights.show()` should be done. I had to open the code in order to understand what I should do and why it is not working.

I think that updating the example with a call to `lights.show()` at the end of it, with sufficient explanation can make the usage of the library a lot easier.

If you agree with that, I can create a relevant pull request.

Thanks,
Omri

**Comment by Gadgetoid** [comment]
You're right! A PR would certainly be appreciated, thank you.
